### ISSUE TITLE
[css-tables] overflow menu depends on inherited table styles

### ISSUE THREAD

**Issue by austingreendev** [zendeskgarden/css-components#124]
## Expectations

For non-native `<table>` implementations (i.e. flex-box and `<div>`s), it is an expectation that the `.c-table__row__cell__overflow` trigger is positioned correctly.

## Reality

![screen shot 2018-09-27 at 11 21 24 am](https://user-images.githubusercontent.com/4030377/46166392-f1344000-c247-11e8-8b32-137301a2f4de.png)

The trigger currently relies on styling only available within a native `<table>`. 

I might be missing something here; so if there are some additional styles we can add on the React side that could be adequate.

###### Fine Print

  - Component: tables
  - Browsers: all

**Comment by jzempel** [comment]
@austin94 I think you need to update your override styling.
* First, set https://github.com/zendeskgarden/react-components/blob/51695232991438a3c43bb7f22b5d4fd08defdb15/packages/tables/src/views/Cell.js#L31 (or `SortableCell`) to `display: flex`.
* Next, override https://github.com/zendeskgarden/react-components/blob/master/packages/tables/src/views/OverflowButton.js to set `margin-top: auto` for any overflow button that is contained in a header row.
