### ISSUE TITLE
Avatar with non square images

### ISSUE THREAD

**Issue by rauschermate** [zendeskgarden/css-components#248]
## Expectations
When using the `Avatar` component I expected to keep image ratios when displaying. 

## Reality

Instead the component would  shrink images other than square ratio.

### Screenshot
<img width="616" alt="Screen Shot 2019-11-06 at 12 45 52 PM" src="https://user-images.githubusercontent.com/13528474/68336662-b54aeb80-0093-11ea-91c6-e03f5f6c311d.png">

## Steps to Reproduce

1. Insert `<Avatar> component with a non square image
2. Notice how the image is being shrank
Note: Easier to see the difference if using the `size="large"` prop

###### Fine Print

  - Component: `Avatar`
  - Browsers: tested in Chrome and Firefox

**Comment by jzempel** [comment]
Fixed by #249
