### ISSUE TITLE
chrome: handling long string in nav items

### ISSUE THREAD

**Issue by zillding** [zendeskgarden/css-components#82]
## Expectations

Not sure about the expected behavior for handling long strings.

## Reality

Different nav items handle long string differently. Main nav item truncates overflowed string while sub item allow the string to expand the parent width.
![screen shot 2018-07-20 at 10 11 00 pm](https://user-images.githubusercontent.com/2175447/43007276-7f2f9cd8-8c6a-11e8-9fd5-72803c9c49a1.png)

After setting a constraint on the width of the sub menu, the overflowed string is truncated
![screen shot 2018-07-20 at 10 11 40 pm](https://user-images.githubusercontent.com/2175447/43007358-add04a1a-8c6a-11e8-8d64-992794d50a3a.png)

If we allow the text to wrap in the sub items:
![screen shot 2018-07-20 at 10 12 09 pm](https://user-images.githubusercontent.com/2175447/43007394-ca6a6dd6-8c6a-11e8-87d4-07f4c65481c8.png)

## Steps to Reproduce

  1. in chrome component, change the content to long strings
  2. add some constraint to the width of container `nav`
  3. add `white-space: normal` to item `button` to see the text wrapping

###### Fine Print

  - Component: chrome
  - Browsers: all

**Comment by austin94** [comment]
@jzempel do you have any historical knowledge of these differences?

@zillding overall there are a _lot_ of variances in how certain projects handle localized (long) strings in the sidebar so I think an un-opinionated approach might be useful.

**Comment by allisonacs** [comment]
IMO, this is something that needs to be consistent between products. From design's perspective, the following should be true:

- We should not use line-height to determine the height of a container in the nav. Doing so creates spaces that are too big between lines when long nav items wrap. The standard type setting is 14/20, we should use that. 
- We should not truncate navigation items. It's incredibly hostile to both i18n __and__ a11y (when you use browser magnification, nav items that normally fit on one line end up being truncated). When it's something as important as navigation, we should never intentionally hide that information. 
- Any icons that might appear inline with the nav items (for example, unread count badges) should me middle-aligned with the first line of the nav item, not centered against the entire nav item container.
