### ISSUE TITLE
Checkboxes with no label are not testable

### ISSUE THREAD

**Issue by anpa** [zendeskgarden/css-components#89]
## Expectations

Checkboxes without a label should be testable/clickable via test tools like Selenium.

## Reality

In a checkbox with no label, the `label` element has no dimensions even though its pseudo element `:before` renders the checkbox itself.

![screen shot 2018-08-07 at 18 13 55](https://user-images.githubusercontent.com/1172767/43788427-acd95dca-9a6d-11e8-94b9-330d18bad227.png)

![screen shot 2018-08-07 at 18 07 22](https://user-images.githubusercontent.com/1172767/43788440-b4dd146c-9a6d-11e8-8165-c123d8f0885e.png)

This makes it difficult to test given that elements without height/width are not considered visible by some testing libraries (and therefore they are not clickable).

## Steps to Reproduce

  1. Create a checkbox with no label;
  1. Target the checkbox with Selenium;
  1. Try to programatically click the checkbox, it fails with an element not visible exception.

###### Fine Print

  - Component: checkbox, toggle, radio
  - Browsers: all

**Comment by austin94** [comment]
👋 Hi @anpa, thanks for opening this.

> This makes it difficult to test given that elements without height/width are not considered visible by some testing libraries (and therefore they are not clickable).

Did you try applying a test attribute or ID to the associated `<input />` that goes along with the label? The label interacts with the input so it should be equivalent.

**Comment by jzempel** [comment]
Closed for now. Please re-open (under `react-components`) if you still have issues. Thanks!
